### ISSUE TITLE
Should `WaitUntil` have `Drop` impl

### ISSUE THREAD

**Issue by Ddystopia** [asynchronics/diatomic-waker#4]
Hello, what do you think about calling `self.wake.unregister()` in `Drop` impl of `WaitUntil` ?

**Comment by sbarral** [comment]
Note that in the nominal case, there is no need to call `unregister` because typically the registration has already been consumed  once `WaitUntil` returns `Poll::Ready`. This is because either the value was immediately available so `register` was never called, or it wasn't and then `notify` will have been called and cleared the `REGISTERED` flag.

So in the end, the only situations when the `REGISTERED` flag is not cleared by the time the `WaitUntil` future is dropped are:
1) the future was cancelled before the future was notified,
2) the value was not available immediately and `register` was thus called, after which the value became available and the future was polled again due to a spurious wake-up before `notify` was called.

So these are relatively uncommon case (especially the second one) and the worse than can happen by leaving the `REGISTERED` flag set is that there will be a spurious task wake-up, which is expensive but harmless.

On the other hand, systematically calling `unregister` in the drop handler would incur a systematic cost of one `fetch_and` even in the nominal case.

I guess we *could* do an atomic read in the drop handler to see if the `REGISTERED` flag is set before we do a `fetch_and`, but I'm not convinced this is worth it TBH.

**Comment by Ddystopia** [comment]
I also think that common case for cancellation is a select loop, and in common use case wait_untill will be recreated again before notification (because of "not blocking the executor" time between cancelling and new select will be a lot smaller then wait time), so it would not result in a spurious wake up

**Comment by Ddystopia** [comment]
Thank you for a detailed answer!
